services:
  release_notes.repository:
    class: AppBundle\Repository\ReleaseNotesRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['AppBundle:ReleaseNotes']

  AppBundle\Repository\ReleaseNotesRepository: '@release_notes.repository'